files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/strings.xml
  - source: /app/src/main/res/values/insight_*.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
  - source: /app/src/main/res/values/exam.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
  - source: /app/src/main/res/values/objectives.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
  - source: /wear/src/main/res/values/strings.xml
    translation: /wear/src/main/res/values-%android_code%/strings.xml
  - source: /app/src/main/res/values/protection.xml
    translation: /app/src/main/res/values-%android_code%/protection.xml
  - source: /app/src/main/res/values/validator.xml
    translation: /app/src/main/res/values-%android_code%/validator.xml
  - source: /core/src/main/res/values/strings.xml
    translation: /core/src/main/res/values-%android_code%/strings.xml
  - source: /dana/src/main/res/values/strings.xml
    translation: /dana/src/main/res/values-%android_code%/strings.xml
  - source: /medtronic/src/main/res/values/strings.xml
    translation: /medtronic/src/main/res/values-%android_code%/strings.xml
  - source: /rileylink/src/main/res/values/strings.xml
    translation: /rileylink/src/main/res/values-%android_code%/strings.xml
