files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/strings.xml
  - source: /app/src/main/res/values/exam.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
  - source: /app/src/main/res/values/objectives.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
  - source: /wear/src/main/res/values/strings.xml
    translation: /wear/src/main/res/values-%android_code%/strings.xml
  - source: /app/src/main/res/values/protection.xml
    translation: /app/src/main/res/values-%android_code%/protection.xml
  - source: /core/src/main/res/values/validator.xml
    translation: /core/src/main/res/values-%android_code%/validator.xml
  - source: /core/src/main/res/values/strings.xml
    translation: /core/src/main/res/values-%android_code%/strings.xml
  - source: /shared/src/main/res/values/strings.xml
    translation: /shared/src/main/res/values-%android_code%/strings.xml
  - source: /pump/combo/src/main/res/values/strings.xml
    translation: /pump/combo/src/main/res/values-%android_code%/strings.xml
  - source: /pump/dana/src/main/res/values/strings.xml
    translation: /pump/dana/src/main/res/values-%android_code%/strings.xml
  - source: /pump/danar/src/main/res/values/strings.xml
    translation: /pump/danar/src/main/res/values-%android_code%/strings.xml
  - source: /pump/medtronic/src/main/res/values/strings.xml
    translation: /pump/medtronic/src/main/res/values-%android_code%/strings.xml
  - source: /pump/omnipod-common/src/main/res/values/strings.xml
    translation: /pump/omnipod-common/src/main/res/values-%android_code%/strings.xml
  - source: /pump/omnipod-dash/src/main/res/values/strings.xml
    translation: /pump/omnipod-dash/src/main/res/values-%android_code%/strings.xml
  - source: /pump/omnipod-eros/src/main/res/values/strings.xml
    translation: /pump/omnipod-eros/src/main/res/values-%android_code%/strings.xml
  - source: /pump/rileylink/src/main/res/values/strings.xml
    translation: /pump/rileylink/src/main/res/values-%android_code%/strings.xml
  - source: /insight/src/main/res/values/strings.xml
    translation: /insight/src/main/res/values-%android_code%/strings.xml
  - source: /insight/src/main/res/values/alert_codes.xml
    translation: /insight/src/main/res/values-%android_code%/alert_codes.xml
  - source: /insight/src/main/res/values/alert_descriptions.xml
    translation: /insight/src/main/res/values-%android_code%/alert_descriptions.xml
  - source: /insight/src/main/res/values/alert_titles.xml
    translation: /insight/src/main/res/values-%android_code%/alert_titles.xml
  - source: /insight/src/main/res/values/exceptions.xml
    translation: /insight/src/main/res/values-%android_code%/exceptions.xml
  - source: /automation/src/main/res/values/strings.xml
    translation: /automation/src/main/res/values-%android_code%/strings.xml
  - source: /pump/eopatch/src/main/res/values/strings.xml
    translation: /pump/eopatch/src/main/res/values-%android_code%/strings.xml
  - source: /pump/diaconn/src/main/res/values/strings.xml
    translation: /pump/diaconn/src/main/res/values-%android_code%/strings.xml
  - source: /pump/pump-common/src/main/res/values/strings.xml
    translation: /pump/pump-common/src/main/res/values-%android_code%/strings.xml
  - source: /openhumans/src/main/res/values/strings.xml
    translation: /openhumans/src/main/res/values-%android_code%/strings.xml
  - source: /implementation/src/main/res/values/strings.xml
    translation: /implementation/src/main/res/values-%android_code%/strings.xml
  - source: /ui/src/main/res/values/strings.xml
    translation: /ui/src/main/res/values-%android_code%/strings.xml
  - source: /plugins/src/main/res/values/strings.xml
    translation: /plugins/src/main/res/values-%android_code%/strings.xml
